// Generated by gencpp from file taticoma_msgs/ControlCommand.msg
// DO NOT EDIT!


#ifndef TATICOMA_MSGS_MESSAGE_CONTROLCOMMAND_H
#define TATICOMA_MSGS_MESSAGE_CONTROLCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace taticoma_msgs
{
template <class ContainerAllocator>
struct ControlCommand_
{
  typedef ControlCommand_<ContainerAllocator> Type;

  ControlCommand_()
    : cmd(0)  {
    }
  ControlCommand_(const ContainerAllocator& _alloc)
    : cmd(0)  {
  (void)_alloc;
    }



   typedef int32_t _cmd_type;
  _cmd_type cmd;



  enum {
    SERVO_PWR_ON = 1,
    SERVO_PWR_OFF = 2,
    PI_POWER_VAR = 3,
    AUDIO_PWR_ON = 4,
    AUDIO_PWR_OFF = 5,
    MOVEMENT_MODE_ON = 6,
    MOVEMENT_MODE_OFF = 7,
    MANUAL_MODE_ON = 8,
    MANUAL_MODE_OFF = 9,
  };


  typedef boost::shared_ptr< ::taticoma_msgs::ControlCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::taticoma_msgs::ControlCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ControlCommand_

typedef ::taticoma_msgs::ControlCommand_<std::allocator<void> > ControlCommand;

typedef boost::shared_ptr< ::taticoma_msgs::ControlCommand > ControlCommandPtr;
typedef boost::shared_ptr< ::taticoma_msgs::ControlCommand const> ControlCommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::taticoma_msgs::ControlCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::taticoma_msgs::ControlCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace taticoma_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'taticoma_msgs': ['/home/ubuntu/ROS/taticoma/taticoma/src/taticoma_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::taticoma_msgs::ControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::taticoma_msgs::ControlCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::taticoma_msgs::ControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::taticoma_msgs::ControlCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::taticoma_msgs::ControlCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::taticoma_msgs::ControlCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::taticoma_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "367a72f93ebfa3ea6e8196068a88b13e";
  }

  static const char* value(const ::taticoma_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x367a72f93ebfa3eaULL;
  static const uint64_t static_value2 = 0x6e8196068a88b13eULL;
};

template<class ContainerAllocator>
struct DataType< ::taticoma_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "taticoma_msgs/ControlCommand";
  }

  static const char* value(const ::taticoma_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::taticoma_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 cmd\n\
\n\
int32 SERVO_PWR_ON=1\n\
int32 SERVO_PWR_OFF=2\n\
int32 PI_POWER_VAR=3\n\
int32 AUDIO_PWR_ON=4\n\
int32 AUDIO_PWR_OFF=5\n\
int32 MOVEMENT_MODE_ON=6\n\
int32 MOVEMENT_MODE_OFF=7\n\
int32 MANUAL_MODE_ON=8\n\
int32 MANUAL_MODE_OFF=9\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::taticoma_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::taticoma_msgs::ControlCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::taticoma_msgs::ControlCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::taticoma_msgs::ControlCommand_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TATICOMA_MSGS_MESSAGE_CONTROLCOMMAND_H
