// Generated by gencpp from file taticoma_msgs/MoveCommand.msg
// DO NOT EDIT!


#ifndef TATICOMA_MSGS_MESSAGE_MOVECOMMAND_H
#define TATICOMA_MSGS_MESSAGE_MOVECOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace taticoma_msgs
{
template <class ContainerAllocator>
struct MoveCommand_
{
  typedef MoveCommand_<ContainerAllocator> Type;

  MoveCommand_()
    : cmd(0)  {
    }
  MoveCommand_(const ContainerAllocator& _alloc)
    : cmd(0)  {
  (void)_alloc;
    }



   typedef int32_t _cmd_type;
  _cmd_type cmd;



  enum {
    STOP_CMD = 1,
    PAUSE_CMD = 2,
    SLEEP_CMD = 3,
    WAKE_CMD = 4,
  };


  typedef boost::shared_ptr< ::taticoma_msgs::MoveCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::taticoma_msgs::MoveCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MoveCommand_

typedef ::taticoma_msgs::MoveCommand_<std::allocator<void> > MoveCommand;

typedef boost::shared_ptr< ::taticoma_msgs::MoveCommand > MoveCommandPtr;
typedef boost::shared_ptr< ::taticoma_msgs::MoveCommand const> MoveCommandConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::taticoma_msgs::MoveCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::taticoma_msgs::MoveCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace taticoma_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'taticoma_msgs': ['/home/ubuntu/ROS/taticoma/taticoma/src/taticoma_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::taticoma_msgs::MoveCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::taticoma_msgs::MoveCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::taticoma_msgs::MoveCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::taticoma_msgs::MoveCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::taticoma_msgs::MoveCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::taticoma_msgs::MoveCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::taticoma_msgs::MoveCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f78f07168f5d781f8449481447d6912";
  }

  static const char* value(const ::taticoma_msgs::MoveCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f78f07168f5d781ULL;
  static const uint64_t static_value2 = 0xf8449481447d6912ULL;
};

template<class ContainerAllocator>
struct DataType< ::taticoma_msgs::MoveCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "taticoma_msgs/MoveCommand";
  }

  static const char* value(const ::taticoma_msgs::MoveCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::taticoma_msgs::MoveCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 cmd\n\
\n\
int32 STOP_CMD=1\n\
int32 PAUSE_CMD=2\n\
int32 SLEEP_CMD=3\n\
int32 WAKE_CMD=4\n\
";
  }

  static const char* value(const ::taticoma_msgs::MoveCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::taticoma_msgs::MoveCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::taticoma_msgs::MoveCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::taticoma_msgs::MoveCommand_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TATICOMA_MSGS_MESSAGE_MOVECOMMAND_H
