# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 1.0
femur_r3:
  ID: 41
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0
tibia_r3:
  ID: 42
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0
