# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 1.0
coha_r1:
  ID: 1
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

coha_r2:
  ID: 2
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

coha_r3:
  ID: 3
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

coha_l1:
  ID: 4
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

coha_l2:
  ID: 5
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

coha_l3:
  ID: 6
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

femur_r1:
  ID: 7
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

femur_r2:
  ID: 8
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

femur_r3:
  ID: 9
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

femur_l1:
  ID: 10
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

femur_l2:
  ID: 11
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

femur_l3:
  ID: 12
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

tibia_r1:
  ID: 13
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

tibia_r2:
  ID: 14
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

tibia_r3:
  ID: 15
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

tibia_l1:
  ID: 16
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0

tibia_l2:
  ID: 17
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0
  
tibia_l3:
  ID: 18
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0
  
