# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 1.0
defs: &servo_params
  Return_Delay_Time: 0
  CW_Angle_Limit: 186
  CCW_Angle_Limit: 840
  Moving_Speed: 0
coha_r1:
  ID: 20
  <<: *servo_params
coha_r2:
  ID: 30
  <<: *servo_params
coha_r3:
  ID: 40
  <<: *servo_params
coha_l1:
  ID: 50
  <<: *servo_params
coha_l2:
  ID: 60
  <<: *servo_params
coha_l3:
  ID: 70
  <<: *servo_params

femur_r1:
  ID: 21
  <<: *servo_params
femur_r2:
  ID: 31
  <<: *servo_params
femur_r3:
  ID: 41
  <<: *servo_params
femur_l1:
  ID: 51
  <<: *servo_params
femur_l2:
  ID: 61
  <<: *servo_params
femur_l3:
  ID: 71
  <<: *servo_params

tibia_r1:
  ID: 22
  <<: *servo_params
tibia_r2:
  ID: 32
  <<: *servo_params
tibia_r3:
  ID: 42
  <<: *servo_params
tibia_l1:
  ID: 52
  <<: *servo_params
tibia_l2:
  ID: 62
  <<: *servo_params
tibia_l3:
  ID: 72
  <<: *servo_params
  