(cl:defpackage taticoma_msgs-msg
  (:use )
  (:export
   "<AUDIOCOMMAND>"
   "AUDIOCOMMAND"
   "<BODYCOMMAND>"
   "BODYCOMMAND"
   "<BODYSTATE>"
   "BODYSTATE"
   "<CONTROLCOMMAND>"
   "CONTROLCOMMAND"
   "<GAITCOMMAND>"
   "GAITCOMMAND"
   "<LEGIKREQUEST>"
   "LEGIKREQUEST"
   "<LEGJOINTSSTATE>"
   "LEGJOINTSSTATE"
   "<LEGPOSITIONSTATE>"
   "LEGPOSITIONSTATE"
   "<LEGSJOINTSSTATE>"
   "LEGSJOINTSSTATE"
   "<MOVECOMMAND>"
   "MOVECOMMAND"
  ))

